In [8]:
import pandas as pd
# from dataframe_cleaner import *
import dataframe_cleaner as dc

In [2]:
df = pd.read_csv("sample_employees.csv")

In [10]:
df = dc.drop_empty(df)

In [13]:
df = dc.fill_empty(df, 'bonus')

In [15]:
for i in range(len(df)):
    print(df['email'][i])

KeyError: 0

In [19]:
dc.fix_index(df)

,first_name,last_name,email,gender,employed_date,department,salary,bonus
0,August,Nelmes,anelmes2@bbb.org,Male,9/7/2014,Accounting,161814.0,14.0
1,Whittaker,Cluet,wcluet6@angelfire.com,Male,4/13/2018,Services,114440.0,11.0
2,Timothee,McVane,tmcvane8@opensource.org,Male,9/5/2013,Support,117430.0,8.0
3,Shell,Zecchinelli,szecchinellib@blogtalkradio.com,Male,2/27/2016,Product Management,154034.0,13.0
4,Dill,Iglesia,diglesiac@g.co,Male,2/19/2018,Support,64334.0,4.0
...,...,...,...,...,...,...,...,...
459,Theobald,Hatley,thatleyri@state.tx.us,Male,5/9/2016,Human Resources,175423.0,12.0
460,Franky,McDell,fmcdellrk@pinterest.com,Female,4/24/2017,Business Development,85666.0,12.0
461,Maurine,Greeson,mgreesonrl@census.gov,Female,8/15/2018,Research and Development,95521.0,7.0
462,Cristy,Nortunen,cnortunenro@freewebs.com,Female,1/28/2016,Engineering,120389.0,2.0
463,Catriona,Rapps,crappsrr@nhs.uk,Female,3/27/2013,Marketing,93899.0,3.0

In [23]:
df = dc.fix_index(df)

In [25]:
df['employed_date'] = dc.fix_dates(df, 'employed_date')

In [26]:
df

,first_name,last_name,email,gender,employed_date,department,salary,bonus
0,August,Nelmes,anelmes2@bbb.org,Male,2014-09-07,Accounting,161814.0,14.0
1,Whittaker,Cluet,wcluet6@angelfire.com,Male,2018-04-13,Services,114440.0,11.0
2,Timothee,McVane,tmcvane8@opensource.org,Male,2013-09-05,Support,117430.0,8.0
3,Shell,Zecchinelli,szecchinellib@blogtalkradio.com,Male,2016-02-27,Product Management,154034.0,13.0
4,Dill,Iglesia,diglesiac@g.co,Male,2018-02-19,Support,64334.0,4.0
...,...,...,...,...,...,...,...,...
459,Theobald,Hatley,thatleyri@state.tx.us,Male,2016-05-09,Human Resources,175423.0,12.0
460,Franky,McDell,fmcdellrk@pinterest.com,Female,2017-04-24,Business Development,85666.0,12.0
461,Maurine,Greeson,mgreesonrl@census.gov,Female,2018-08-15,Research and Development,95521.0,7.0
462,Cristy,Nortunen,cnortunenro@freewebs.com,Female,2016-01-28,Engineering,120389.0,2.0
463,Catriona,Rapps,crappsrr@nhs.uk,Female,2013-03-27,Marketing,93899.0,3.0